swagger: '2.0'
info:
  version: '1.0'
  title: Sample Collection
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: echo.getpostman.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /get:
    get:
      description: 'TODO: Add Description'
      summary: First request!
      tags:
      - Test Folder
      operationId: First request!
      produces:
      - application/json
      parameters:
      - name: name
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /get
          headers:
            name: Abhijit
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: First request!
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
